sonar.projectKey=aceestver
sonar.projectName=Aceestver Flask Application
sonar.sources=app
sonar.tests=tests
sonar.exclusions=tests/conftest.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true