apiVersion: v1
kind: Service
metadata:
  name: aceestver-service
spec:
  selector:
    app: aceestver   # must match the label in your Deployment's pod template
  ports:
    - protocol: TCP
      port: 80        # external port exposed by the LoadBalancer
      targetPort: 5000 # matches containerPort in deployment.yaml
  type: LoadBalancer
